### ISSUE TITLE
Update the readme with detailed installation steps

### ISSUE THREAD

**Issue by anclrii** [anclrii/Storj-Exporter#10]

**Comment by Cmdrd** [comment]
What all are you wanting to cover for this? I can put more time into expanding the README with additional instructions. I have some more tweaks and such to put in but if you had any ideas I can also write them up.

**Comment by anclrii** [comment]
Thanks, any help much appreciated! 
So I already had a prometheus/grafana stack when I started with storj and it's setup with ansible with no docker. Not really a common case. I was thinking to add the following

* Since storj relies on docker I think docker bootstrap of prometheus stack would be easiest starting point but I never tried this. Adding something like https://github.com/vegasbrianc/prometheus/blob/master/docker-compose.yml to this repo along with instructions would be good, but I'd want to test on storage node first.
* I don't see a point adding installation steps for prometheus in the readme here, since there's official documentation available. Maybe worth adding a link to the docs. Same for grafana. 
* Adding some examples for prometheus configs for storj would be good to have in the readme. The ones that appeared on https://forum.storj.io/t/prometheus-storj-exporter would do.
* _May be useful to add details full setup instructions for different platforms in wiki later._

If you are going to pick this up don't expect to cover everything in one go. Add one small thing and let's merge it with a PR.

**Comment by anclrii** [comment]
Added a docker-compose example here https://github.com/anclrii/Storj-Exporter-dashboard/tree/master/quick_start 
Need to add links to this repo readme now

**Comment by anclrii** [comment]
readme updated
