### ISSUE TITLE
Show outdated version as a single status/metric in grafana

### ISSUE THREAD

**Issue by anclrii** [anclrii/Storj-Exporter#21]
Show outdated version as a single status/metric in grafana:
    * we may find a way to do this in Grafana with just the versions returned as strings (unlikely :) )
    * we can consider adding a 3-rd version metric like `storj_version_status` that will compare versions within exporter code. We can add something like https://stackoverflow.com/a/11887825
    * there are other ideas discussed in #18

_Originally posted by @anclrii in https://github.com/anclrii/Storj-Exporter/pull/18#issuecomment-578835155_

**Comment by Cmdrd** [comment]
The second option about breaking down into substrings then comparing based on those values may be the overall least amount of work and probably makes the most sense code-wise. Would probably also be the most readable for code and understanding the purpose. 3 lines of code is pretty maintainable.

**Comment by anclrii** [comment]
api now returns uptodate status and this is now visualised as green/red circle status on the dashboard, also added a current storagenode version in the summary table beside it

![image](https://user-images.githubusercontent.com/40526988/99838013-5fdb6280-2b60-11eb-84e5-b5253d4ab92a.png)
