### ISSUE TITLE
Use satellite's url instead of id for more readability

### ISSUE THREAD

**Issue by syberalexis** [anclrii/Storj-Exporter#27]
Satellite ID is not human readable in grafana dashboard.
I think, it's better to display satellite's url.

I tried it in my instance of exporter and it's works good.
I can make a PR, if you validate this issue.

**Comment by syberalexis** [comment]
I don't see your PR #26, sorry

**Comment by anclrii** [comment]
url label added in https://github.com/anclrii/Storj-Exporter/pull/26
