### ISSUE TITLE
No distinction between regular and repair upload in earnings

### ISSUE THREAD

**Issue by frequentsailor** [anclrii/Storj-Exporter#32]
Hello,

first of all I love Storj-Exporter and the corresponding Grafana dashboards. I have learned a lot getting it all to work for my node. Thank you for your effort.

Recently I noticed that the earnings reported in the Grafana dashboard and the earnings reported with the [script from ReneSmeekes](https://github.com/ReneSmeekes/storj_earnings).

I think it is because Storj-Exporter doesn't take the different prices for regular and repair upload into account.

**Comment by kevinkk525** [comment]
The earnings are calculated on the dashboard, not the exporter.

**Comment by anclrii** [comment]
> I think it is because Storj-Exporter doesn't take the different prices for regular and repair upload into account.

True, it was calculated in grafana expressions and was never 100% precise. Fortunately api returns payout estimates now and this is directly exported and visualised on the updated dashboard along with `held` amount. This should now match what's displayed on the official dashboard.
