### ISSUE TITLE
High CPU usage on exporter and node

### ISSUE THREAD

**Issue by kevinkk525** [anclrii/Storj-Exporter#34]
With the new update I can see a high cpu usage periodically on the exporter and the storagenode. As soon as I stop the exporter, the CPU usage on the node goes away. 
![grafik](https://user-images.githubusercontent.com/9607123/90064896-b75d6d00-dceb-11ea-8fb0-1114f3e874cb.png)
![grafik](https://user-images.githubusercontent.com/9607123/90065153-263ac600-dcec-11ea-8d15-991eca3bdc59.png)

It looks like something is trying to pull information all the time, even though my prometheus configuration only pulls data every 30 seconds. 

It's the same for all 3 nodes running on the host.

**Comment by kevinkk525** [comment]
This is strange, I just tried all recent version and it is the same with every version (except <=0.25, those throw errors since the API changed).
And my first node doesn't throw any errors now so I removed that error from the first post. However, the weird CPU consumption stays.
It causes quite some reads (which my zfs has in cache) and 1 cpu core to go to 100% for a short duration. 
![grafik](https://user-images.githubusercontent.com/9607123/90136712-e66bf100-dd74-11ea-9dce-2e05bef17635.png)
![grafik](https://user-images.githubusercontent.com/9607123/90136748-ef5cc280-dd74-11ea-85d0-d6e7fca26b44.png)

I thought the exporter only does something when prometheus scrapes it?
My scrape is every 30 seconds:
![grafik](https://user-images.githubusercontent.com/9607123/90136822-0ef3eb00-dd75-11ea-90f1-cc68787630c9.png)

But the cpu spikes in the node occur every 5 seconds.

**Comment by anclrii** [comment]
Hey thanks for reporting and yes I noticed the same too. It looks like with some recent updates in storagenode itself the api calls got heavier on cpu and it takes longer to respond. I see the same with raw api calls to storagenode. Though I still need to look into it properly to confirm. Exporter logic is pretty simple and not much changed recently. Most recent update fixes metrics for suspended and disqualified status. Either way I'll need to take a closer look.

**Comment by anclrii** [comment]
On my node that's about 1.7T exporter takes about 6s to respond. Every time I call it I see `storagenode` cpu go up to ~100% for 6s while exporter process uses little cpu in process list (top):
```
# time curl -s http://127.0.0.1:9651/metrics >/dev/null

real    0m5.799s
user    0m0.019s
sys     0m0.031s
```

Exporter calls storagenode api once for each sat in a loop with a call like `127.0.0.1:14002/api/sno/satellite/<satid>`. When I call it manually it takes about 1s to respond for each sat. Again `storagenode` spikes cpu to 100% for the duration of the call:
```
# time curl -s 127.0.0.1:14002/api/sno/satellite/12rfG3sh9NCWiX3ivPjq2HtdLmbqCrvHVEzJubnzFzosMuawymB >/dev/null

real    0m0.980s
user    0m0.022s
sys     0m0.009s
```

My top output at the time of scrape shows 120% cpu used by storagenode and 2% exporter:
```
  PID USER      PR  NI    VIRT    RES    SHR S  %CPU %MEM     TIME+ COMMAND
 6848 root      20   0  742584  41780  14572 S 120.0  1.0   1607:59 ./storagenode run --config-dir 
18228 root      20   0   25756  18816   3896 S   2.3  0.5  13:18.78 python ./storj-exporter.py
```

Something has changed in the way storagenode responds to api calls making it heavier on CPU. I bet if we benchmark the built-in dashboard it got heavier too.. unless it's pulling data directly from db. 

Can you try to time the same curl calls on your side please so we can compare?

> I thought the exporter only does something when prometheus scrapes it?

Yes, and I'm not sure why you see 5s spikes, would need more info to explain this.

**Comment by kevinkk525** [comment]
My node has 6TB
```
# time curl -s 127.0.0.1:14002/api/sno/satellite/12rfG3sh9NCWiX3ivPjq2HtdLmbqCrvHVEzJubnzFzosMuawymB >/dev/null

real    0m0.247s
user    0m0.006s
sys     0m0.006s

# time curl -s http://127.0.0.1:9651/metrics >/dev/null

real    0m1.492s
user    0m0.005s
sys     0m0.004s
```

My times are a lot lower than yours, probably because my zfs has it all cached in RAM.

So you don't see a spike every 5 seconds? Only every 30 seconds with each scrape?

**Comment by kevinkk525** [comment]
The CPU spikes continue even if prometheus is down, so it doesn't have anything to do with the scraping. Without having looked at the code, there must be something polling the storagenode all the time.

**Comment by kevinkk525** [comment]
I don't know what happened but after a server restart the spikes only appear every 30 seconds when it is being scraped.. Not sure why I had 5 seconds spikes before even though I restarted the exporter container and the prometheus container.

**Comment by anclrii** [comment]
Huh this was a long shot, glad it helped
