### ISSUE TITLE
storj_sat_month_storage sums up to the same value as returned by storj_sat_summary

### ISSUE THREAD

**Issue by anclrii** [anclrii/Storj-Exporter#5]
`storj_sat_month_storage` sums up to the same value as returned by `storj_sat_summary`. If that's the case then `storj_sat_month_storage` must be removed.

Initially assumed `storj_sat_month_storage` would expose storage change for a given month but seems to be total storage.

**Comment by Cmdrd** [comment]
Can this be closed as it is no longer present in the code?

**Comment by anclrii** [comment]
removed outdated metrics in #26
