### ISSUE TITLE
Remove LastPinged information from storj_node_info

### ISSUE THREAD

**Issue by kevinkk525** [anclrii/Storj-Exporter#56]
Can we remove the LastPinged information from storj_node_info? It clutters the metric horribly with (in my opinion) no relevant information. Where is the lastPinged information even useful? And if it really is, can't we change it to a normal metric?

https://github.com/anclrii/Storj-Exporter/blob/fe5dba595ee15ab9a53afc8922e10848d7edefd8/storj-exporter.py#L82

**Comment by anclrii** [comment]
I had my doubts when adding this one, there's a few others that don't make much sense I think and a few that are duplicate values fetched from different parts of api. I was just adding everything available though and wasn't sure what's going to end up on the dashboards.

Let's clarify the use-case for `LastPinged` maybe before we remove it?

**Comment by kevinkk525** [comment]
Well theoretically lastPinged can be used to detect if the node is offline. But I haven't really found a good way to work with labels in grafana so for alerting and calculations it would need to be the value of a metric and not the value of a label. I would have no problem keeping it as a normal metric as it just stores an ever increasing timestamp. Haven't checked in grafana if you can make a graph that alerts you if it doesn't change for a certain period though..

**Comment by anclrii** [comment]
Removed in https://github.com/anclrii/Storj-Exporter/pull/65
