### ISSUE TITLE
Not working on some nodes

### ISSUE THREAD

**Issue by ayaseen** [anclrii/Storj-Exporter#8]
I have tried the script and docker container but every time I got this error:

Traceback (most recent call last):
  File "./storj-exporter.py", line 126, in <module>
    REGISTRY.register(StorjCollector())
  File "/usr/local/lib/python3.7/site-packages/prometheus_client/registry.py", line 24, in register
    names = self._get_names(collector)
  File "/usr/local/lib/python3.7/site-packages/prometheus_client/registry.py", line 64, in _get_names
    for metric in desc_func():
  File "./storj-exporter.py", line 111, in collect
    storj_sat_day_storage.add_metric(["atRestTotal", sat], self.sat_data[sat]['storageDaily'][-1]['atRestTotal'])
TypeError: 'NoneType' object is not subscriptable

**Comment by ayaseen** [comment]
By the way I removed this line and it's working, I have no idea why

**Comment by anclrii** [comment]
It seems api returns null for some fields for new nodes until they get some traffic going. Though I don't have a new node to reproduce.

Can you test https://github.com/anclrii/Storj-Exporter/blob/dev/storj-exporter.py and see if it helps?

Or try new tag for docker:
```
docker pull  anclrii/storj-exporter:0.2.4 ; docker stop storj-exporter ; docker rm storj-exporter ; docker run -d --restart=unless-stopped --link=storagenode --name=storj-exporter -p 9651:9651 anclrii/storj-exporter:0.2.4
```

**Comment by ayaseen** [comment]
Hello,

It's working fine now.

Thanks
